
run_flye: true
run_flye_hapdup: true

# estimated genome size (for example, 5m or 2.6g)
flye_genome_size: 3.1g

# do not collapse alternative haplotypes
flye_keep_haplotypes: true
# do not output contigs representing alternative haplotypes
flye_no_alt_contigs: false
